apiVersion: apps/v1
kind: Deployment
metadata:
  name: containers-mutator-deployment
  namespace: containers-mutator
  labels:
    app: containers-mutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containers-mutator
  template:
    metadata:
      labels:
        app: containers-mutator
    spec:
      containers:
        - name: containers-mutator
          image: khanhngobackend/containers-mutator:latest
          imagePullPolicy: IfNotPresent
          args:
          - -port=8443
          - -sidecarCfgFile=/etc/webhook/config/mutator.config.yaml
          - -tlsCertFile=/etc/webhook/certs/cert.pem
          - -tlsKeyFile=/etc/webhook/certs/key.pem
          - -alsologtostderr
          - -v=4
          - 2>&1
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
          - name: webhook-config
            mountPath: /etc/webhook/config
      volumes:
      - name: webhook-certs
        secret:
          secretName: containers-mutator-certs
      - name: webhook-config
        configMap:
          name: containers-mutator-configmap
