apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: podmu-cfg
  labels:
    app: podmu
webhooks:
- name: podmu
  clientConfig:
    service:
      name: podmu-svc
      namespace: podmu
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  # objectSelector: # for further narrowing down selected objects
  #   matchLabels:
  #     podmu: enabled
  namespaceSelector:
    matchLabels:
      podmu: enabled

# Add the following label to indicate which namespace podmu should operate on:
#   podmu: enabled