apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: containers-mutator-cfg
  labels:
    app: containers-mutator
webhooks:
- name: containers-mutator.khanhngobackend.io
  clientConfig:
    service:
      name: containers-mutator-svc
      namespace: containers-mutator
      path: "/mutate"
    caBundle: ${CA_BUNDLE}
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  objectSelector:
    matchLabels:
      containers-mutator: enabled
  namespaceSelector:
    matchLabels:
      containers-mutator: enabled
