apiVersion: v1
kind: Service
metadata:
  name: containers-mutator-svc
  namespace: containers-mutator
  labels:
    app: containers-mutator
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: containers-mutator
